### PR TITLE
Resolves Issue #25 - add SpMV test suites

### PR DESCRIPTION
**Pull request by albertlu03**
The calls to the generator are each of the matrices within the two papers, dense1000 is not in suitesparse. Each output is written to its own subdirectory.

### CODE REVIEW

**Review by willow-ahrens — CHANGES_REQUESTED** [review]
This looks good! Let's add a dense generator to the matrix generator, and then put all of this logic inside the generate.jl script so that we can just do

`julia src/generate.jl spmv vuduc02`

and get the whole suite of matrices

**Comment by willow-ahrens** [comment]
This is looking good! Your commit message says "dense generator" but I don't see a dense generator, is that right? Also, we don't need the shell script anymore I think

**Comment by albertlu03** [comment]
I might have misunderstood, what exactly constitutes a "dense generator"? I kind of just assumed the vuduc and langr functions were those.

**Comment by willow-ahrens** [comment]
https://willowahrens.io/Finch.jl/dev/guides/tensor_formats/
https://en.wikipedia.org/wiki/Sparse_matrix

**Pull request merged**
